#
# CSE183 Assignment 7
#

openapi: '3.0.3'

info:
  description: CSE183 Assignment 7
  version: 0.1.0
  title: CSE183 Assignment 7

servers:
  - url: http://localhost:3010

paths:
  /v0/mail:
    get:
      description: Returns all EMail
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailResponse'
        404:
          description: Not Found
        500:
          description: Internal Server Error
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      parameters:
      - name: mailbox
        in: query
        description: The mailbox of emails to retrieve
        required: false
        schema:
          type: string
        style: form
    post:
      description: Posts an email to the Sent Mailbox
      responses:
        201:
          description: Email Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mail'
        500: 
          description: Email has unexpected properties
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostMail'
              
  /v0/mail/{id}:
    get:
      description: Gets a specific email based on UUID
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mail'
        404:
          description: Not Found
        500:
          description: Internal Server Error
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      parameters:
      - name: id
        in: path
        description: The UUID of the email to retrieve
        required: true
        schema:
          type: string
        style: simple
    put:
      description: Move email by id into specified Mailbox
      responses:
        204:
          description: Successfully put email into mailbox
        404:
          description: Email not Found
        409: 
          description: Incoming email cannot be moved to sent
      parameters:
      - name: id
        in: path
        description: The UUID of the email to retrieve
        required: true
        schema:
          type: string
        style: simple
      - name: mailbox
        in: query
        description: The destination mailbox for the email
        required: false
        schema:
          type: string
        style: form
  
  /v0/mailboxes:
    get:
      description: gets a list of all maiboxes
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MailboxList'
        500:
          description: Internal Server Error
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v0/starred/{id}:
    put:
      description: Changes the starred status of the email by id
      responses:
        200:
          description: Success
        500:
          description: Internal Server Error
        404:
          description: Email not found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      parameters:
      - name: id
        in: path
        description: The UUID of the email to retrieve
        required: true
        schema:
          type: string
        style: simple
      - name: star
        in: query
        description: The new starred status of the email
        required: true
        schema:
          type: boolean
        style: form
      


components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    EmailResponse:
      type: array
      items:
        $ref: '#/components/schemas/Mailbox'
    
    Mailbox:
      type: object
      properties:
        name:
          type: string
        mail:
          type: array
          items:
            $ref: '#/components/schemas/MailboxList'

    PostMail:
      type: object
      properties:
        to-name:
          type: string
        to-email:
          type: string
        subject:
          type: string
        received:
          type: string
        content:
          type: string

    Mail:
      type: object
      properties:
        id:
          type: string
        to-name:
          type: string
        to-email:
          type: string
        from-name:
          type: string
        from-email:
          type: string
        subject:
          type: string
        received:
          type: string
        content:
          type: string
        starred:
          type: boolean
        mailbox:
          type: string
        read:
          type: boolean

    MailboxList:
      type: object
      properties:
        list:
          type: array
          items:
            type: string
